### ISSUE TITLE
'*' in key

### ISSUE THREAD

**Issue by mdigger** [recoilme/slowpoke#15]
Ключом для сохранения является произвольный массив байт. Он может быть порожден как счетчиком (с преобразованием числа в байты), так и строкой. Обычно ключ будет нормален. Но что произойдет с логикой работы выборки по ключам (`slowpoke.Keys(…)`), если в самом ключе будет `'*'`?

Насколько я понимаю, я могу ожидать, что получу следующую запись после указанного ключа, и это будет работать до тех пор, пока чисто случайно не окажется, что ключ заканчивается на `'*'`. И вместо выборки со следующего ключа, я получу выборку все, начинающихся на префикс.

Я прав? Или я "дую на воду"?

**Comment by mdigger** [comment]
Мне кажется, что изменение параметров в `Keys()` является более простым способом, чем введение специальных символов, которые еще и не очень то введешь, потому что ключ является набором произвольных байт. Конечно, это приведет к несовместимости API, но тут уж решать вам.

**Comment by recoilme** [comment]
да я честно говоря не могу представить как добиться некорректного поведения, даже если все данные будут целиком из звездочек, ну и звездочки и звездочки

Если будет какой то конкретный кейс можно будет подумать что делать

**Comment by mdigger** [comment]
Я потому и спросил, что для меня это является потенциальной проблемой.

Ключ у меня формируется из двух счетчиков: скажем, раздел и документ в нем. Соответственно, ключ представляет из себя массив байт, в котором лежит бинарное представление этих двух счетчиков. При выборках только из конкретного раздела, если ключ будет заканчиваться на `2c`, получается не совсем тот результат, который ожидался.

**Comment by recoilme** [comment]
можно пример некорректного поведения пожалуйста?

**Comment by mdigger** [comment]
Например, запрос с указанием идентификатора: 
> If from not `nil` - return keys after from (from not included) If last byte of from == `'*'` -- return keys with this prefix

```
[ka1, ka2, ka3, kb1. kb2. kb3 ... k*1, k*2, k*3, kn1, kn2, kn3]

ka -> [ka3...kn3]
kb -> [kb1...kn3]
k* -> [ka1...kn3], а ожидаю [k*1…kn3]
```

**Comment by recoilme** [comment]
вывод будет такой если я правильно понял вопрос:
```
func TestAsterix(t *testing.T) {
	f := "test/TestAsterix.db"
	k := [...]string{"ka1", "ka2", "ka3", "kb1", "kb2", "k*1", "k*2", "k*3", "kn1", "kn2"}
	for _, v := range k {
		Set(f, []byte(v), nil)
	}
	k1, _ := Keys(f, []byte("ka"), uint32(0), uint32(0), true)
	fmt.Println(k1) //[]
	ka, _ := Keys(f, []byte("ka*"), uint32(0), uint32(0), true)
	for _, s := range ka {
		fmt.Println(string(s))
	}
	/*
		ka1
		ka2
		ka3
	*/

	kast, _ := Keys(f, []byte("k**"), uint32(0), uint32(0), true)
	for _, s := range kast {
		fmt.Println(string(s))
	}
	/*
		k*1
		k*2
		k*3
	*/
	fmt.Println("kfrom")
	kfrom, _ := Keys(f, []byte("k*1"), uint32(0), uint32(0), true)
	for _, s := range kfrom {
		fmt.Println(string(s))
	}
	/*
	k*2
	k*3
	ka1
	ka2
	ka3
	kb1
	kb2
	kn1
	kn2
	*/
}

```

**Comment by mdigger** [comment]
Не совсем…

```
func TestAsterix(t *testing.T) {
    f := "test/TestAsterix.db"
    DeleteFile(f)
    k := [...]string{"k#", "k#1", "k#2", "k#3", "k$", "k$1", "k$2", "k$3", "k*", "k*1", "k*2", "k*3", "kn", "kn1", "kn2"}
    for _, v := range k {
        Set(f, []byte(v), nil)
    }
    for _, k := range []string{"k#", "k#*", "k$", "k$*", "k*", "k**", "kn", "kn*"} {
        k1, _ := Keys(f, []byte(k), 0, 0, true)
        fmt.Printf("%s: %s\n", k, k1)
    }
}
```
```
k#: [k#1 k#2 k#3 k$ k$1 k$2 k$3 k* k*1 k*2 k*3 kn kn1 kn2]
k#*: [k# k#1 k#2 k#3]
k$: [k$1 k$2 k$3 k* k*1 k*2 k*3 kn kn1 kn2]
k$*: [k$ k$1 k$2 k$3]
k*: [k# k#1 k#2 k#3 k$ k$1 k$2 k$3 k* k*1 k*2 k*3 kn kn1 kn2]
k**: [k* k*1 k*2 k*3]
kn: [kn1 kn2]
kn*: [kn kn1 kn2]
```

**Comment by mdigger** [comment]
Как эту проблему избежать — **понятно!** Вопрос только в том, что не окажется ли это *вдруг* неожиданным поведением для кого-то? Ведь отследить её будет достаточно проблематично, особенно на не очень большом количестве данных. Зато, по мере их роста, эта проблема может проявиться просто из-за счетчика.

**Comment by mdigger** [comment]
Даже сократим:
```
func TestAsterix(t *testing.T) {
	f := "test/TestAsterix.db"
	DeleteFile(f)
	k := [...]string{"k#", "k$", "k*", "kn"}
	for _, v := range k {
		Set(f, []byte(v), nil)
	}
	for _, k := range []string{"k#", "k$", "k*", "k**", "kn"} {
		k1, _ := Keys(f, []byte(k), 0, 0, true)
		fmt.Printf("%s: %s\n", k, k1)
	}
}
```
```
k#:  [k$ k* kn]
k$:  [k* kn]
k*:  [k# k$ k* kn]
k**: [k*]
kn:  []
```

**Comment by recoilme** [comment]
наглядный  пример, спасибо! 
да вроде кодовая база то крохотная, надеюсь разберутся)
а если нет - покажу им этот пример, как иллюстрацию)
