### ISSUE TITLE
В slowpoke нет режима «nosync»

### ISSUE THREAD

**Issue by temoto** [recoilme/slowpoke#19]
В двух словах: не нашел код, который реализует очень нужную мне фичу "нет режима nosync". Такое заявление было только на хабре и в коде "with sync at end", в readme не сказано, поэтому не знаю насколько вам интересно, может быть новый курс без sync и это приемлимо.

- slowpoke.Set = return pudge.Set
- pudge.Set = Open(filename, nil).Set
- pudge.Open(filename, cfg*Config) cfg=nil -> DefaultConfig
- DefaultConfig.SyncInterval = 0 sec, 0 - disable sync
- `pudge.db.Close()` сделал бы нужные вызовы `.Sync()`, но его не видно

**Comment by recoilme** [comment]
Не уверен что понял вопрос.
Если интервал синхронизации не задан (равен нулю), sync делает операционная система (на свое усмотрение). Метод Close - делает sync перед закрытием в любом случае.
https://github.com/recoilme/pudge/blob/master/pudge.go#L148

**Comment by temoto** [comment]
Наверное, вопрос можно сформулировать так: что slowpoke не делает sync, теряет данные, это противоречит заявлению на хабре и в исходниках "with sync at end". Вы знаете, это умышленно, или это баг?

**Comment by recoilme** [comment]
в первой версии slowpoke был только один режим - с принудительным sync - после каждой записи: https://habr.com/ru/post/354224/

"Все команды записи в slowpoke атомарны, и завершаются командой sync (синхронизация данных). Дело в том, что современные файловые системы при записи в файл, пишут по сути в буфер. И в случае падения операционной системы буфер будет потерян. Большинство баз данных имеет режим nosync (может называться по разному, но суть в том, что операция синхронизации очень медленная, особенно это заметно на старых винчестерах и для победы в бенчмарках и для ускорения записи используется данный режим)."

Для пакетной записи - предлагалось использовать sets. Что оказалось не очень удобно на практике. В новом движке ( https://github.com/recoilme/pudge ) - нет режима принудительного sync - на каждую запись. И появилась возможность его отключения, те по сути nosync. Либо - интервальная синхронизация по таймеру. 

Те статья на хабре не соответствует текущей версии.

**Comment by recoilme** [comment]
Те слоупоке сейчас - обертка над https://github.com/recoilme/pudge
Посмотрите  [pudge](https://github.com/recoilme/pudge) - там более удобное и высокоуровневое апи

**Comment by temoto** [comment]
Да-да, я цитировал код pudge в первом сообщении только потому что смотрел его.

Короче резолюция такая, что это не баг и все в курсе. Может быть вам будет интересен патч документации типа `- // with sync at end` ?

**Comment by recoilme** [comment]
Отлично. Я думаю если возникнет подобный вопрос - достаточно будет сослаться на это issue
