### ISSUE TITLE
Добавить методы для хранения структур

### ISSUE THREAD

**Issue by Supme** [recoilme/slowpoke#3]
Например, как вариант, использовать для кодирования/декодирования gob

**Comment by recoilme** [comment]
Добавлен пример с gob: 
https://github.com/recoilme/slowpoke/blob/master/example/example.go#L90

slowpoke предоставляет универсальный бинарный интерфейс. Задача выбора метода кодирования -  лежит на клиенте. Примеры различных подходов:

Иногда удобен будет json (например его можно читать в javascript), пример:
https://github.com/recoilme/slowpoke/blob/master/simpleserver/slowpokesrv_test.go

В каких то случаях удобен бинарный формат так как он самый компактный: 
общий пример - https://play.golang.org/p/jcn6ldeAEX , 
частный пример, в бинарном формате хранятся ключи в слоупоке:
https://github.com/recoilme/slowpoke/blob/master/slowpoke.go#L540

Для сервера удобен protobuf, пример 
https://github.com/recoilme/okdb/blob/master/api/api.proto

И где-то в конце списка - gob. Он избыточен по сравнению с бинарными форматами, так как, хранит поля и тип структур и не универсален (нет библиотек под другие языки).

**Comment by recoilme** [comment]
Смержил в мастер
